version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: real_estate_db
    environment:
      POSTGRES_DB: Швецов_real_estate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  postgres_data: