FROM node:24-slim

# Создаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY ./backend/package*.json ./backend/

# Устанавливаем зависимости
WORKDIR /app/backend
RUN npm install

# Копируем остальные файлы backend
COPY ./backend .

# Копируем frontend
COPY ./frontend /app/frontend

# Открываем порт
EXPOSE 3000

# Запускаем приложение
CMD ["node", "server.js"]