services:
  customer-backend-1:
    build: 
      context: ./customer-app
      dockerfile: Dockerfile.backend
    volumes:
      - ./customer-app/backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - WS_SERVER=ws://websocket-server:9000
      - NODE_ENV=development
    ports:
      - "3001:3000"

  customer-backend-2:
    build: 
      context: ./customer-app
      dockerfile: Dockerfile.backend
    volumes:
      - ./customer-app/backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - WS_SERVER=ws://websocket-server:9000
      - NODE_ENV=development
    ports:
      - "3002:3000"

  customer-backend-3:
    build: 
      context: ./customer-app
      dockerfile: Dockerfile.backend
    volumes:
      - ./customer-app/backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - WS_SERVER=ws://websocket-server:9000
      - NODE_ENV=development
    ports:
      - "3003:3000"

  admin-backend:
    build: 
      context: ./admin-app
      dockerfile: Dockerfile.backend
    volumes:
      - ./admin-app/backend:/app
      - /app/node_modules
      - ./admin-app/backend/data:/app/data
    environment:
      - PORT=8080
      - WS_SERVER=ws://websocket-server:9000
      - NODE_ENV=development
    ports:
      - "8089:8080"

  websocket-server:
    build: 
      context: ./websocket-server
      dockerfile: Dockerfile
    volumes:
      - ./websocket-server:/app
      - /app/node_modules
    environment:
      - PORT=9000
      - NODE_ENV=development
    ports:
      - "9009:9000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "89:80"
    depends_on:
      - customer-backend-1
      - customer-backend-2
      - customer-backend-3
      - admin-backend
      - websocket-server
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  node_modules: